name: Java Build

on: [push]

jobs:
  Build-Artifacts:
    runs-on: linux-amd64
    steps:
    - run: set
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'
        server-id: gitea
        server-password: DEPLOY_TOKEN
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
    - name: Checkout application repository
      uses: actions/checkout@v4
      with:
        repo-token: ${{ secrets.GIT_TOKEN }}     
    - name: Build artifacts with Maven
      run: mvn clean install -Dgpg.passphrase="${{ secrets.GPG_PASS }}"
    - name: Publish artifacts
      run: mvn deploy
    - name: Archive job artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          target/*pom
          target/*jar
          target/*asc